name: "nirog_data_warehouse"
version: "1.0.0"
config-version: 2

profile: "nirog_data_warehouse"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +on_schema_change: "sync_all_columns"
  nirog_data_warehouse:
    +project: |
      {%- if  target.name == "development" -%} nirog-development
      {%- elif target.name == "production"  -%} nirog-production
      {%- else -%} invalid_project
      {%- endif -%}
    +dataset: |
      {%- if  target.name == "development" -%} development_default
      {%- elif target.name == "production"  -%} production_default
      {%- else -%} invalid_project
      {%- endif -%}
    +persist_docs:
      relation: true
      columns: true
    01_base:
      dataset: base
    02_stage_core:
      dataset: stage_core
    03_stage_aggregate:
      dataset: stage_aggregate
    04_report:
      dataset: report
