nirog_data_warehouse:

  target: development

  outputs:

    development:
      type: bigquery
      method: service-account
      project: nirog-development
      dataset: development_default
      threads: 32
      timeout_seconds: 1800
      priority: interactive
      fixed_retries: 1

    production:
      type: bigquery
      method: service-account
      project: nirog-production
      dataset: production_default
      threads: 32
      timeout_seconds: 1800
      priority: interactive
      fixed_retries: 1
