version: 2

models:

  #########################
  # Base - DBO - MData BP #
  #########################

  - name: bse_dbo_mdata_bp
    config:
      alias: "mdata_bp"

  #################################
  # Base - DBO - MData Glucose HB #
  #################################

  - name: bse_dbo_mdata_glucose_hb
    config:
      alias: "mdata_glucose_hb"

  ########################################
  # Base - DBO - MData Patient OBS Gynae #
  ########################################

  - name: bse_dbo_mdata_patient_obs_gynae
    config:
      alias: "mdata_patient_obs_gynae"

  ########################
  # Base - DBO - Patient #
  ########################

  - name: bse_dbo_patient
    config:
      alias: "patient"

  ##########################
  # Base - DBO - Workplace #
  ##########################

  - name: bse_dbo_workplace
    config:
      alias: "workplace"

  #########################
  # Base - DBO - District #
  #########################

  - name: bse_dbo_district
    config:
      alias: "district"

  #########################
  # Base - DBO - Upazila #
  #########################

  - name: bse_dbo_upazila
    config:
      alias: "upazila"
