name: "nirog_data_warehouse"
version: "1.0.0"
config-version: 2

profile: "nirog_data_warehouse"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nirog_data_warehouse:
    +project: |
      {%- if  target.name == "development" -%} nirog-development
      {%- elif target.name == "production" -%} nirog-production
      {%- else -%} invalid-project
      {%- endif -%}
    persist_docs:
      relation: true
      columns: true
    01_landing:
      dataset: landing
      landing_dbo:
        dataset: landing_dbo
      landing_external:
        dataset: landing_external
    02_base:
      dataset: base
      base_dbo:
        dataset: base_dbo
      base_external:
        dataset: base_external
    03_stage_core:
      dataset: stage_core
    04_stage_aggregate:
      dataset: stage_aggregate
    05_report:
      dataset: report
