version: 2

models:

  ################################
  # Report - Daywise Patient HTN #
  ################################

  - name: rep_patient_htn
    config:
      alias: patient_htn

  ###############################
  # Report - Daywise Patient DM #
  ###############################

  - name: rep_patient_dm
    config:
      alias: patient_dm

  #################################
  # Report - HTN Info Period Wise #
  #################################

  - name: rep_htn_info_period_wise
    config:
      alias: htn_info_period_wise
  
  ################################
  # Report - DM Info Period Wise #
  ################################

  - name: rep_dm_info_period_wise
    config:
      alias: dm_info_period_wise
