version: 2

models:

  #####################################
  # Aggregate - Daily HTN Information #
  #####################################

  - name: stg_agg_htn_info_daily
    config:
      alias: htn_info_daily

  ####################################
  # Aggregate - Daily DM Information #
  ####################################

  - name: stg_agg_dm_info_daily
    config:
      alias: dm_info_daily

