{{-
    config(
        materialized = "table",
        tags = ["execute_daily", "report", "export"]
    )
-}}

SELECT
    pe.health_center_name AS `Health_Center_Name`,
    mdst.patient_id AS `Patient_ID`,
    mdst.collected_date AS `Collection_Date`,
    pe.registration_id AS `Registration_ID`,
    pe.given_name AS `Given_Name`,
    pe.family_name AS `Family_Name`,
    pe.gender_code AS `Gender`,
    pe.birth_date AS `Birth_Date`,
    pe.age AS `Age`,
    pe.cell_number AS `Mobile_Number`,
    mdst.followup_date AS `Followup_Date`,
    mdst.height AS `Height`,
    mdst.weight AS `Weight`,
    mdst.bmi AS `BMI`,
    pe.gender_description AS `Gender_Description`,
    mdst.heart_rate AS `Heart_Rate`,
    mdst.bp_systolic_1 AS `BP_Systolic_1`,
    mdst.bp_diastolic_1 AS `BP_Diastolic_1`,
    mdst.bp_systolic_2 AS `BP_Systolic_2`,
    mdst.bp_diastolic_2 AS `BP_Diastolic_2`,
    mdst.bp_systolic AS `BP_Systolic`,
    mdst.bp_diastolic AS `BP_Diastolic`,
    mdst.bp_collected_date AS `BP_Collection_Date`,
    mdst.rbg AS `RBG`,
    mdst.fbg AS `FBG`,
    mdst.hrs_from_last_eat AS `Hours_Since_Last_Meal`,
    mdst.hemoglobin AS `Hemoglobin`,
    mdst.anemia_severity AS `Anemia_Severity`,
    mdst.cough_greater_than_month AS `Cough_Greater_Than_Month`,
    mdst.lgerf AS `LGERF`,
    mdst.night_sweat AS `Night_Sweat`,
    mdst.weight_loss AS `Weight_Loss`,
    mdst.gravida AS `Gravida`,
    mdst.still_birth AS `Still_Birth`,
    mdst.miscarraige_or_abortion AS `Miscarraige_or_Abortion`,
    mdst.mr AS `MR`,
    mdst.living_birth AS `Living_Birth`,
    mdst.living_male AS `Living_Male`,
    mdst.living_female AS `Living_Female`,
    mdst.child_mortality_0_to_1 AS `Child_Mortality_0_to_1`,
    mdst.child_mortality_below_5 AS `Child_Mortality_Below_5`,
    mdst.child_mortality_over_5 AS `Child_Mortality_Over_5`,
    mdst.lmp AS `LMP`,
    mdst.contraception_method_code AS `Contraception_Method_Code`,
    mdst.other_contraception_method AS `Other_Contraception_Method`,
    mdst.menstruation_product_code AS `Menstruation_Product_Code`,
    mdst.menstruation_product_usage_time_code AS `Menstruation_Product_Usage_Time`,
    mdst.other_menstruation_product AS `Other_Menstruation_Product`,
    mdst.other_menstruation_product_usage_time AS `Other_Menstruation_Product_Usage_Time`,
    mdst.prescribed_drugs AS `Prescribed_Drugs`,
    mdst.chief_complain_with_duration AS `Chief_Complain_with_Duration`,
    mdst.rx_details AS `RX_Details`,
    mdst.provisional_diagnosis_details AS `Provisional_Diagnosis`,
    mdst.physical_findings AS `Physical_Findings`,
    mdst.patient_illness_history AS `Patient_Illness_History`,
    mdst.family_illness_history AS `Family_Illness_History`,
    mdst.social_behavior_history AS `Social_Behavior_History`,
    mdst.vaccination AS `Vaccination`,

    -- VACCINE INFORMATION --
    IF(mdst.is_vac_bcg, 1, 0) AS `Vaccinated_BCG`,
    IF(mdst.is_vac_pentavalent, 1, 0) AS `Vaccinated_Pentavalent`,
    IF(mdst.is_vac_pcv, 1, 0) AS `Vaccinated_PCV`,
    IF(mdst.is_vac_opv, 1, 0) AS `Vaccinated_OPV`,
    IF(mdst.is_vac_mrs, 1, 0) AS `Vaccinated_MRS`,
    IF(mdst.is_vac_measles, 1, 0) AS `Vaccinated_Measles`,
    IF(mdst.is_vac_chicken_pox, 1, 0) AS `Vaccinated_Chicken_Pox`,
    IF(mdst.is_vac_covid_19, 1, 0) AS `Vaccinated_Covid_19`,

    -- DIAGNOSIS INFORMATION --
    IF(mdst.is_cancer, 1, 0) AS `Diagnosed_Cancer`,
    IF(mdst.is_malaria, 1, 0) AS `Diagnosed_Malaria`,
    IF(mdst.is_skin_disease, 1, 0) AS `Diagnosed_Skin_Disease`,
    IF(mdst.is_asthma, 1, 0) AS `Diagnosed_Asthma`,
    IF(mdst.is_hypertension, 1, 0) AS `Diagnosed_Hypertension`,
    IF(mdst.is_dm, 1, 0) AS `Diagnosed_Diabetes`,
    IF(mdst.is_surgery, 1, 0) AS `Diagnosed_Surgery`,
    IF(mdst.is_tb, 1, 0) AS `Diagnosed_TB`,
    IF(mdst.is_typhoid, 1, 0) AS `Diagnosed_Typhoid`,
    IF(mdst.is_fracture_injury, 1, 0) AS `Diagnosed_Fracture_Injury`,
    IF(mdst.is_hepatitis, 1, 0) AS `Diagnosed_Hepatitis`,
    IF(mdst.is_ihd, 1, 0) AS `Diagnosed_IHD`,
    IF(mdst.is_depression, 1, 0) AS `Diagnosed_Depression`,
    IF(mdst.is_stroke, 1, 0) AS `Diagnosed_Stroke`,
    IF(mdst.is_dengue, 1, 0) AS `Diagnosed_Dengue`,

    IF(mdst.is_father_cancer, 1, 0) AS `Diagnosed_Father_Cancer`,
    IF(mdst.is_father_malaria, 1, 0) AS `Diagnosed_Father_Malaria`,
    IF(mdst.is_father_skin_disease, 1, 0) AS `Diagnosed_Father_Skin_Disease`,
    IF(mdst.is_father_asthma, 1, 0) AS `Diagnosed_Father_Asthma`,
    IF(mdst.is_father_hypertension, 1, 0) AS `Diagnosed_Father_Hypertension`,
    IF(mdst.is_father_dm, 1, 0) AS `Diagnosed_Father_Diabetes`,
    IF(mdst.is_father_surgery, 1, 0) AS `Diagnosed_Father_Surgery`,
    IF(mdst.is_father_tb, 1, 0) AS `Diagnosed_Father_TB`,
    IF(mdst.is_father_typhoid, 1, 0) AS `Diagnosed_Father_Typhoid`,
    IF(mdst.is_father_fracture_injury, 1, 0) AS `Diagnosed_Father_Fracture_Injury`,
    IF(mdst.is_father_hepatitis, 1, 0) AS `Diagnosed_Father_Hepatitis`,
    IF(mdst.is_father_ihd, 1, 0) AS `Diagnosed_Father_IHD`,
    IF(mdst.is_father_depression, 1, 0) AS `Diagnosed_Father_Depression`,
    IF(mdst.is_father_stroke, 1, 0) AS `Diagnosed_Father_Stroke`,
    IF(mdst.is_father_dengue, 1, 0) AS `Diagnosed_Father_Dengue`,

    IF(mdst.is_mother_cancer, 1, 0) AS `Diagnosed_Mother_Cancer`,
    IF(mdst.is_mother_malaria, 1, 0) AS `Diagnosed_Mother_Malaria`,
    IF(mdst.is_mother_skin_disease, 1, 0) AS `Diagnosed_Mother_Skin_Disease`,
    IF(mdst.is_mother_asthma, 1, 0) AS `Diagnosed_Mother_Asthma`,
    IF(mdst.is_mother_hypertension, 1, 0) AS `Diagnosed_Mother_Hypertension`,
    IF(mdst.is_mother_dm, 1, 0) AS `Diagnosed_Mother_Diabetes`,
    IF(mdst.is_mother_surgery, 1, 0) AS `Diagnosed_Mother_Surgery`,
    IF(mdst.is_mother_tb, 1, 0) AS `Diagnosed_Mother_TB`,
    IF(mdst.is_mother_typhoid, 1, 0) AS `Diagnosed_Mother_Typhoid`,
    IF(mdst.is_mother_fracture_injury, 1, 0) AS `Diagnosed_Mother_Fracture_Injury`,
    IF(mdst.is_mother_hepatitis, 1, 0) AS `Diagnosed_Mother_Hepatitis`,
    IF(mdst.is_mother_ihd, 1, 0) AS `Diagnosed_Mother_IHD`,
    IF(mdst.is_mother_depression, 1, 0) AS `Diagnosed_Mother_Depression`,
    IF(mdst.is_mother_stroke, 1, 0) AS `Diagnosed_Mother_Stroke`,
    IF(mdst.is_mother_dengue, 1, 0) AS `Diagnosed_Mother_Dengue`,

    IF(mdst.is_siblings_cancer, 1, 0) AS `Diagnosed_Siblings_Cancer`,
    IF(mdst.is_siblings_malaria, 1, 0) AS `Diagnosed_Siblings_Malaria`,
    IF(mdst.is_siblings_skin_disease, 1, 0) AS `Diagnosed_Siblings_Skin_Disease`,
    IF(mdst.is_siblings_asthma, 1, 0) AS `Diagnosed_Siblings_Asthma`,
    IF(mdst.is_siblings_hypertension, 1, 0) AS `Diagnosed_Siblings_Hypertension`,
    IF(mdst.is_siblings_dm, 1, 0) AS `Diagnosed_Siblings_Diabetes`,
    IF(mdst.is_siblings_surgery, 1, 0) AS `Diagnosed_Siblings_Surgery`,
    IF(mdst.is_siblings_tb, 1, 0) AS `Diagnosed_Siblings_TB`,
    IF(mdst.is_siblings_typhoid, 1, 0) AS `Diagnosed_Siblings_Typhoid`,
    IF(mdst.is_siblings_fracture_injury, 1, 0) AS `Diagnosed_Siblings_Fracture_Injury`,
    IF(mdst.is_siblings_hepatitis, 1, 0) AS `Diagnosed_Siblings_Hepatitis`,
    IF(mdst.is_siblings_ihd, 1, 0) AS `Diagnosed_Siblings_IHD`,
    IF(mdst.is_siblings_depression, 1, 0) AS `Diagnosed_Siblings_Depression`,
    IF(mdst.is_siblings_stroke, 1, 0) AS `Diagnosed_Siblings_Stroke`,
    IF(mdst.is_siblings_dengue, 1, 0) AS `Diagnosed_Siblings_Dengue`,

    IF(mdst.is_aunt_cancer, 1, 0) AS `Diagnosed_Aunt_Cancer`,
    IF(mdst.is_aunt_malaria, 1, 0) AS `Diagnosed_Aunt_Malaria`,
    IF(mdst.is_aunt_skin_disease, 1, 0) AS `Diagnosed_Aunt_Skin_Disease`,
    IF(mdst.is_aunt_asthma, 1, 0) AS `Diagnosed_Aunt_Asthma`,
    IF(mdst.is_aunt_hypertension, 1, 0) AS `Diagnosed_Aunt_Hypertension`,
    IF(mdst.is_aunt_dm, 1, 0) AS `Diagnosed_Aunt_Diabetes`,
    IF(mdst.is_aunt_surgery, 1, 0) AS `Diagnosed_Aunt_Surgery`,
    IF(mdst.is_aunt_tb, 1, 0) AS `Diagnosed_Aunt_TB`,
    IF(mdst.is_aunt_typhoid, 1, 0) AS `Diagnosed_Aunt_Typhoid`,
    IF(mdst.is_aunt_fracture_injury, 1, 0) AS `Diagnosed_Aunt_Fracture_Injury`,
    IF(mdst.is_aunt_hepatitis, 1, 0) AS `Diagnosed_Aunt_Hepatitis`,
    IF(mdst.is_aunt_ihd, 1, 0) AS `Diagnosed_Aunt_IHD`,
    IF(mdst.is_aunt_depression, 1, 0) AS `Diagnosed_Aunt_Depression`,
    IF(mdst.is_aunt_stroke, 1, 0) AS `Diagnosed_Aunt_Stroke`,
    IF(mdst.is_aunt_dengue, 1, 0) AS `Diagnosed_Aunt_Dengue`,

    IF(mdst.is_grandparents_cancer, 1, 0) AS `Diagnosed_Grandparents_Cancer`,
    IF(mdst.is_grandparents_malaria, 1, 0) AS `Diagnosed_Grandparents_Malaria`,
    IF(mdst.is_grandparents_skin_disease, 1, 0) AS `Diagnosed_Grandparents_Skin_Disease`,
    IF(mdst.is_grandparents_asthma, 1, 0) AS `Diagnosed_Grandparents_Asthma`,
    IF(mdst.is_grandparents_hypertension, 1, 0) AS `Diagnosed_Grandparents_Hypertension`,
    IF(mdst.is_grandparents_dm, 1, 0) AS `Diagnosed_Grandparents_Diabetes`,
    IF(mdst.is_grandparents_surgery, 1, 0) AS `Diagnosed_Grandparents_Surgery`,
    IF(mdst.is_grandparents_tb, 1, 0) AS `Diagnosed_Grandparents_TB`,
    IF(mdst.is_grandparents_typhoid, 1, 0) AS `Diagnosed_Grandparents_Typhoid`,
    IF(mdst.is_grandparents_fracture_injury, 1, 0) AS `Diagnosed_Grandparents_Fracture_Injury`,
    IF(mdst.is_grandparents_hepatitis, 1, 0) AS `Diagnosed_Grandparents_Hepatitis`,
    IF(mdst.is_grandparents_ihd, 1, 0) AS `Diagnosed_Grandparents_IHD`,
    IF(mdst.is_grandparents_depression, 1, 0) AS `Diagnosed_Grandparents_Depression`,
    IF(mdst.is_grandparents_stroke, 1, 0) AS `Diagnosed_Grandparents_Stroke`,
    IF(mdst.is_grandparents_dengue, 1, 0) AS `Diagnosed_Grandparents_Dengue`,

    IF(mdst.is_other_cancer, 1, 0) AS `Diagnosed_Other_Cancer`,
    IF(mdst.is_other_malaria, 1, 0) AS `Diagnosed_Other_Malaria`,
    IF(mdst.is_other_skin_disease, 1, 0) AS `Diagnosed_Other_Skin_Disease`,
    IF(mdst.is_other_asthma, 1, 0) AS `Diagnosed_Other_Asthma`,
    IF(mdst.is_other_hypertension, 1, 0) AS `Diagnosed_Other_Hypertension`,
    IF(mdst.is_other_dm, 1, 0) AS `Diagnosed_Other_Diabetes`,
    IF(mdst.is_other_surgery, 1, 0) AS `Diagnosed_Other_Surgery`,
    IF(mdst.is_other_tb, 1, 0) AS `Diagnosed_Other_TB`,
    IF(mdst.is_other_typhoid, 1, 0) AS `Diagnosed_Other_Typhoid`,
    IF(mdst.is_other_fracture_injury, 1, 0) AS `Diagnosed_Other_Fracture_Injury`,
    IF(mdst.is_other_hepatitis, 1, 0) AS `Diagnosed_Other_Hepatitis`,
    IF(mdst.is_other_ihd, 1, 0) AS `Diagnosed_Other_IHD`,
    IF(mdst.is_other_depression, 1, 0) AS `Diagnosed_Other_Depression`,
    IF(mdst.is_other_stroke, 1, 0) AS `Diagnosed_Other_Stroke`,
    IF(mdst.is_other_dengue, 1, 0) AS `Diagnosed_Other_Dengue`

FROM

{{ ref("stg_cor_mdata_super_table") }} AS mdst

LEFT OUTER JOIN {{ ref("stg_cor_patient_extended") }} AS pe
    ON
        mdst.patient_id = pe.patient_id

WHERE
    TRUE
    AND pe.registration_id IS NOT NULL
