version: 2

models:

  ##################################
  # Stage Core - MData Super Table #
  ##################################

  - name: stg_cor_mdata_super_table
    config:
      alias: "mdata_super_table"

  ##################################
  # Stage Core - Patient Extended #
  ##################################

  - name: stg_cor_patient_extended
    config:
      alias: "patient_extended"

  #################################
  # Stage Core - Area Super Table #
  #################################

  - name: stg_cor_area_super_table
    config:
      alias: "area_super_table"
